"""Build release artifacts for the current platform.

    python packaging/build.py [--repo owner/repo] [--skip-installer]

Windows: dist/DJManager-<v>-portable.exe (single file) and, with Inno Setup installed,
         dist/DJManager-<v>-setup.exe (built from the one-folder build in build/onedir).
Linux:   dist/dj-manager-<v>-linux-x86_64 (single file).

--repo is baked into the build as the default GitHub repository for self-updates.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PKG = ROOT / "packaging"
DIST = ROOT / "dist"
BUILD = ROOT / "build"
IS_WINDOWS = sys.platform.startswith("win")

sys.path.insert(0, str(ROOT))
from djmanager import __version__  # noqa: E402


def write_build_info(repo: str) -> Path:
    path = ROOT / "djmanager" / "_build_info.py"
    path.write_text(f'"""Generated by packaging/build.py."""\n\nUPDATE_REPO = {repo!r}\n', encoding="utf-8")
    return path


def pyinstaller(name: str, onefile: bool, workdir: Path, distdir: Path) -> None:
    sep = ";" if IS_WINDOWS else ":"
    args = [
        sys.executable, "-m", "PyInstaller", str(PKG / "launcher.py"),
        "--name", name, "--noconfirm", "--clean",
        "--distpath", str(distdir), "--workpath", str(workdir), "--specpath", str(workdir),
        "--add-data", f"{ROOT / 'djmanager' / 'static'}{sep}djmanager/static",
        "--paths", str(ROOT),
        # uvicorn picks loops/protocols dynamically
        "--collect-submodules", "uvicorn",
        "--collect-data", "certifi",  # CA bundle for HTTPS, see util.ssl_context
        "--hidden-import", "djmanager._build_info",
        "--onefile" if onefile else "--onedir",
    ]
    if IS_WINDOWS:
        args += ["--windowed", "--icon", str(PKG / "windows" / "icon.ico"), "--collect-all", "webview"]
    else:
        # pywebview needs system GTK/Qt bindings on Linux; the binary opens the browser.
        args += ["--exclude-module", "webview"]
    subprocess.run(args, check=True, cwd=ROOT)


def publish(src: Path, dst: Path) -> None:
    # Unlink first: overwriting a binary that is currently running fails on Linux
    # ("Text file busy"); the running process keeps its own copy of the old file.
    dst.unlink(missing_ok=True)
    shutil.copy2(src, dst)


def find_iscc() -> str | None:
    found = shutil.which("iscc")
    if found:
        return found
    for base in (os.environ.get("ProgramFiles(x86)"), os.environ.get("ProgramFiles")):
        if base and (Path(base) / "Inno Setup 6" / "ISCC.exe").exists():
            return str(Path(base) / "Inno Setup 6" / "ISCC.exe")
    return None


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY", ""), help="GitHub owner/repo for updates")
    parser.add_argument("--skip-installer", action="store_true")
    args = parser.parse_args()

    DIST.mkdir(exist_ok=True)
    info = write_build_info(args.repo)
    print(f"Building DJ Manager {__version__} (update repo: {args.repo or 'none'})")
    try:
        if IS_WINDOWS:
            pyinstaller("DJManager", True, BUILD / "onefile", BUILD / "onefile-dist")
            portable = DIST / f"DJManager-{__version__}-portable.exe"
            publish(BUILD / "onefile-dist" / "DJManager.exe", portable)
            print(f"-> {portable}")
            if not args.skip_installer:
                pyinstaller("DJManager", False, BUILD / "onedir", BUILD / "onedir-dist")
                iscc = find_iscc()
                if not iscc:
                    sys.exit("Inno Setup 6 not found (install it or pass --skip-installer)")
                subprocess.run([iscc, f"/DAppVersion={__version__}", f"/DSourceDir={BUILD / 'onedir-dist' / 'DJManager'}",
                                f"/DOutputDir={DIST}", str(PKG / "windows" / "installer.iss")], check=True)
                print(f"-> {DIST / f'DJManager-{__version__}-setup.exe'}")
        else:
            pyinstaller("dj-manager", True, BUILD / "onefile", BUILD / "onefile-dist")
            binary = DIST / f"dj-manager-{__version__}-linux-x86_64"
            publish(BUILD / "onefile-dist" / "dj-manager", binary)
            binary.chmod(0o755)
            print(f"-> {binary}")
    finally:
        info.unlink(missing_ok=True)


if __name__ == "__main__":
    main()
